baseurl = "https://unlimitedfocus.github.io/"
languageCode = "ko"
title = "jungchoon's dev log"
theme= "hugo-theme-geppaku"
googleAnalytics = "UA-44684084-1"
disqusShortname = "unlimitedfocus-github"
publishDir = "unlimitedfocus.github.io"

[author]
	name = "JungChoon Park"

	# Please set account ids. This is Optional values
	linkedin = "unlimitedfocus"
	github   = "unlimitedfocus"

[params]
	[params.sharebutton]
		# If you want to display share buttons set these
		# This is Optional values
		facebook = true
		google   = true
		facebookAppId = "1452601768192967"
		# pocket   = true

	[params.adsense]
		# If you want to display Google adsense set these
		# This is Optional values
		# 1. Create file written of the adsense tag into the directory "layouts/partials"
		# 2. Please set file path name omitted "layouts/partials"
		# sidebar = "adsense/sidebar.html"
		# content = "adsense/content.html"
