baseurl = "https://unlimitedfocus.github.io/"
languageCode = "ko"
title = "jungchoon's dev log"
theme= "hugo-theme-geppaku"
googleAnalytics = "UA-44684084-1"
disqusShortname = "unlimitedfocus-github"
# publishDir = "docs"
publishDir = "unlimitedfocus.github.io"

[author]
	# If you want to display author information set these
	# This is Optional values
	name = "JungChoon Park"

	# Please set account ids
	# This is Optional values
	linkedin = "unlimitedfocus"
	github   = "unlimitedfocus"
	# twitter  = "your twitter id"
	# tumblr   = "your tumblr id"

[params]
	[params.sharebutton]
		# If you want to display share buttons set these
		# This is Optional values
		# twitter  = true
		facebook = true
		# tumblr   = true
		# hatena   = true # hatena is Japanese social media
		google   = true
		pocket   = true
		# Please set id when you want to display facebook
		# facebookAppId = "your app id"

	[params.adsense]
		# If you want to display Google adsense set these
		# This is Optional values
		# 1. Create file written of the adsense tag into the directory "layouts/partials"
		# 2. Please set file path name omitted "layouts/partials"
		# sidebar = "adsense/sidebar.html"
		# content = "adsense/content.html"
